services:
  db:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    container_name: mobauto-db
    environment:
      POSTGRES_USER: mobauto
      POSTGRES_PASSWORD: mobauto
      POSTGRES_DB: mobauto
    ports:
      - 2345:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    external: false
